In [1]:
#Functions

def greet_user(): #defining a function called "greet_user" and giving any information
                   # the function needs inside the paranthesis.
    print('Hello')
    
#we defined a function that prints the string "Hello"

greet_user()

Hello


In [2]:
#We want to define a function that prints "Hello name". This time, we want the function
#to greet a specific person 

def greet_user(person):
    print("Hello " + person + ".")
    
greet_user('jesse')

Hello jesse.


In [3]:
greet_user('Adam')

Hello Adam.


In [ ]:
#Here 'person' is called a parameter. The value we give to a parameter is called an 'argument'
#When we say greet_user('jesse'), the word jesse is an argument.

In [4]:
#1. Write a function called display_message() that prints one sentence telling everyone what
# you are learning about in this chapter. Call the function, and make sure the message
#displays correctly

def display_message():
    print("In this chapter, we are learning about functions.")
    
display_message()

In this chapter, we are learning about functions.


In [6]:
#2 Write a funciton called favorite_book() that accepts one parameter, title. The function 
#should print a message, such as One of my favorite books is Alice in The Wonderland. Call
#the function, making sure to include a book title as an argument in the funciton call.

def favorite_book(title):
    print("One of my favorite books is " + title + ".")
    
favorite_book("Crash Course Python")
favorite_book("Alice in The Wonderland")

One of my favorite books is Crash Course Python.
One of my favorite books is Alice in The Wonderland.


In [8]:
#Sometimes, you will need more than one parameter.

def describe_pet(animal_type, pet_name):
    print("I have a " + animal_type + ".")
    print("My " + animal_type + "'s name is " + pet_name + ".")
    

describe_pet('hamster', 'Harry') #Remember to pay attention to the order when passing arguments



I have a hamster.
My hamster's name is Harry.


In [11]:
describe_pet('cat', 'Willie')

I have a cat.
My cat's name is Willie.


In [12]:
#If we don't pay attention to the order, we may end up with an undesired result.

describe_pet('Willie', 'cat')

I have a Willie.
My Willie's name is cat.


In [ ]:
#Avoiding Argument Errors p.140. The number of arguments we pass need to equal the number
#of parameters the function has. Otherwise, we will get an error. Let's look at an example.



In [13]:
describe_pet()

TypeError: describe_pet() missing 2 required positional arguments: 'animal_type' and 'pet_name'

In [15]:
#3. Write a function called make_shirt() that accepts a size and the 
#text of a message that should be printed on this shirt. The function
#should print a sentence summarizing the size of the shirt and the 
#message printed on it. 

def make_shirt(size, text):
    print("The shirt should be of size " + size + " with " + text + " written on it.")
    
make_shirt('small', 'python')
make_shirt('medium', 'java')

The shirt should be of size small with python written on it.
The shirt should be of size medium with java written on it.


In [20]:
#4. Write a function called describe_city() that accepts the name of a 
#city and its country. The function should print a simple sentence, such 
#as Reykjavik is in Iceland. Call your function for three different 
#cities.

def describe_city(city, country):
    print(city + " is in " + country + ".")
    
describe_city("Ankara", "Turkey")
describe_city("Albany", "The United States")
describe_city("Kuwait city", "Kuwait")


Ankara is in Turkey.
Albany is in The United States.
Kuwait city is in Kuwait.


In [22]:
#Return Values p.141

#we may use "return" instead of print. 

def get_name(first_name, last_name):
    full_name= first_name + ' ' + last_name
    return full_name

#When we use return, we have get_name(first_name, last_name) = full_name

musician = get_name('Jimi', "Hendrix")
print(musician)

#In this case get_name('Jimi', "Hendrix") is set to equal full_name
#(whatever we wrote for "return")


Jimi Hendrix


In [23]:
#The parameters in a function do not need to be variables, we could
#use lists, tuples, and so on.

def greet_user(names): #here, the parameter is a list called names
    for name in names:
        msg = "Hello, " + name + "!"
        print(msg)
        
greet_user(['hannah', 'ty', 'margot'])

#So we passed a list ['hannah', 'ty', 'margot'] for the parameter names

Hello, hannah!
Hello, ty!
Hello, margot!


In [26]:
#Passing an arbitrary number of arguments p. 151

#Sometimes, we will not know the number of arguments we will need. 
#In this case, we may use a list for the parameter (like we did 
#in the previous example), or we could use a tuple with an asterisk as
#we will see below.

def make_pizza(toppings): #we can use a list for our parameter since
                            #we don't know how many toppings will be 
                            #requested.
    print(toppings)
    
make_pizza(['pepperoni'])
make_pizza(['mushrooms', 'green peppers', 'extra cheese'])

['pepperoni']
['mushrooms', 'green peppers', 'extra cheese']


In [28]:
#We can also use a more complicated function

def make_pizza(toppings):
    print("Making a pizza with the following toppings:")
    for topping in toppings:
        print('- ' + topping)
        
make_pizza(['pepperoni'])
make_pizza(['mushrooms', 'green peppers', 'extra cheese'])

Making a pizza with the following toppings:
- pepperoni
Making a pizza with the following toppings:
- mushrooms
- green peppers
- extra cheese


In [30]:
#There is another way to include any number of arguments, and that's
#by using a tuple with an asterisk

def make_pizza(*toppings):
    print(toppings)
    
#Here, *toppings created an empty tuple called toppings and added the
#the arguements given in make_pizza to the tuple toppings
    
make_pizza('pepperoni')
make_pizza('mushrooms', 'green peppers', 'extra cheese')


('pepperoni',)
('mushrooms', 'green peppers', 'extra cheese')


In [31]:
def make_pizza(*toppings):
    print("Making a pizza with the following toppings:")
    for topping in toppings:
        print('- ' + topping)
        
make_pizza('pepperoni')
make_pizza('mushrooms', 'green peppers', 'extra cheese')

Making a pizza with the following toppings:
- pepperoni
Making a pizza with the following toppings:
- mushrooms
- green peppers
- extra cheese


In [33]:
#if we want to add more parameters to make_pizza, we can do that by
#writings all the parameters first and the parameter *toppings the last

def make_pizza(size, *toppings):
    print("Making a " + str(size) + "-inch pizza with the following toppings:")
    for topping in toppings:
        print("- " + topping)
        
make_pizza(16, 'pepperoni')

make_pizza(12, 'mushrooms', 'green peppers', 'extra cheese')

Making a 16-inch pizza with the following toppings:
- pepperoni
Making a 12-inch pizza with the following toppings:
- mushrooms
- green peppers
- extra cheese


In [ ]:
#5. Write a function that accepts a list of items a person wants on a 
#sandwich. The function should have one parameter that collects as many
#items as the function call provides, and it should print a summary
#of the sandwich that is being ordered. Call the function three times,
#using a different number of arguments each time.

In [37]:
def make_sandwich(*list):
    print("Adding the following to my sandwich:")
    for xy in list:
        print("- " + xy)
        
        
make_sandwich('olives', 'cheese', 'tomatoe')
make_sandwich('cheese', 'turkey')
make_sandwich('tuna')

Adding the following to my sandwich:
- olives
- cheese
- tomatoe
Adding the following to my sandwich:
- cheese
- turkey
Adding the following to my sandwich:
- tuna


In [ ]:
#Numpy Arrays from the book "Python programming for numerical methods:
#a guide for engineers and scientists"

In [40]:
#To use numpy arrays we need to import the numpy library. A numpy array
#is very similar to a list. 

import numpy as np

x = np.array([1, 4, 3])
print(x)

[1 4 3]


In [42]:
#We can also define matrices using numpy arrays. To define matrices,
#we write the first row, then the second row, and so on.

y = np.array([[1, 4, 3], [9, 2, 7]])
print(y)

[[1 4 3]
 [9 2 7]]


In [43]:
#y.shape gives us the number of rows in our numpy array followed by 
#the number of columns


y.shape

(2, 3)

In [44]:
#y.size gives us the number of entries that we have


y.size

6

In [49]:
#When we want to create a list starting from one number (example 1)
#and ending at another number (example 2000) with a certain 
#increment (example 1)

z = np.arange(1, 2000, 1)
print(z)

#If I want the same numpy array with an increment of 2

zz = np.arange(1, 2000, 2)
print(zz)

zzz= np.arange(1, 2000, 10)
print(zzz)

[   1    2    3 ... 1997 1998 1999]
[   1    3    5    7    9   11   13   15   17   19   21   23   25   27
   29   31   33   35   37   39   41   43   45   47   49   51   53   55
   57   59   61   63   65   67   69   71   73   75   77   79   81   83
   85   87   89   91   93   95   97   99  101  103  105  107  109  111
  113  115  117  119  121  123  125  127  129  131  133  135  137  139
  141  143  145  147  149  151  153  155  157  159  161  163  165  167
  169  171  173  175  177  179  181  183  185  187  189  191  193  195
  197  199  201  203  205  207  209  211  213  215  217  219  221  223
  225  227  229  231  233  235  237  239  241  243  245  247  249  251
  253  255  257  259  261  263  265  267  269  271  273  275  277  279
  281  283  285  287  289  291  293  295  297  299  301  303  305  307
  309  311  313  315  317  319  321  323  325  327  329  331  333  335
  337  339  341  343  345  347  349  351  353  355  357  359  361  363
  365  367  369  371  373  375  377  379 

In [51]:
xyz = np.arange(0.5, 3, 0.5)
print(xyz)

[0.5 1.  1.5 2.  2.5]


In [52]:
#np.linspace gives us a numpy array starting from one number an ending
#at another. Here the third parameter is the number of elements that
#we want that are evenly spaced out.

np.linspace(3,9,10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [53]:
print(x)

[1 4 3]


In [54]:
print(x[1])

4


In [55]:
print(x[1:]) #all elements starting from the second element

[4 3]


In [56]:
print(x[-1]) #the last element of x

3


In [57]:
print(y)

[[1 4 3]
 [9 2 7]]


In [58]:
y[0,1]

4

In [59]:
y[0,:]

array([1, 4, 3])

In [60]:
y[:,-1]

array([3, 7])

In [61]:
y[:, [0,2]]

array([[1, 3],
       [9, 7]])

In [62]:
#We can define a numpy array of any size consisting entirely of zeros
#or ones

np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
a = np.arange(1,7) #the increment is 1 by default
print(a)

[1 2 3 4 5 6]


In [70]:
a[3]

4

In [71]:
a[:3] =1 #all entries from the 0th position up to the 2nd position is 
#defined as 1

print(a)

[1 1 1 4 5 6]


In [73]:
a[1:4] = [9,7,8]
print(a)

[1 9 7 8 5 6]


In [77]:
b = np.array([[1,2], [3,4]])
print(b)

[[1 2]
 [3 4]]


In [78]:
b+2

array([[3, 4],
       [5, 6]])

In [79]:
b-2

array([[-1,  0],
       [ 1,  2]])

In [80]:
b*2

array([[2, 4],
       [6, 8]])

In [81]:
b/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [82]:
b**2

array([[ 1,  4],
       [ 9, 16]])

In [83]:
d = np.array([[3,4],[5,6]])

b+d

array([[ 4,  6],
       [ 8, 10]])

In [84]:
b-d

array([[-2, -2],
       [-2, -2]])

In [85]:
b*d #note: this is NOT matrix multiplication, but component-wise multiplication


array([[ 3,  8],
       [15, 24]])

In [86]:
b/d

array([[0.33333333, 0.5       ],
       [0.6       , 0.66666667]])

In [87]:
b**d

array([[   1,   16],
       [ 243, 4096]])

In [88]:
#Recall that the transpose of a matrix is when the rows become the columns

b.T

array([[1, 3],
       [2, 4]])

In [89]:
x = np.array([1, 4, 9])
z = np.sqrt(x)
print(z)

[1. 2. 3.]


In [92]:
x = np.array([1, 4, 9, 5, 3])
y = np.array([0, 5, 8, 4, 5])
x>3

array([False,  True,  True,  True, False])

In [93]:
x > y

array([ True, False,  True,  True, False])

In [95]:
#We are defining y to be a list containing those elements of x >3

y = x[x>3]
print(y)

[4 9 5]


In [96]:
x[x>3] = 0 #I'm defining elements in x greater than 3 to equal 0
print(x)

[1 0 0 0 3]
