 AI sekansa hoj geldiniz.... bu saatten sonra burası numpy sekansıdır. iyi uçuşlar dilerim.

Bu Numpy nedir arkadaş. Hemen anlatalım. Açılımı numerical pyhtondan geliyor. Genelde bilimsel hesaplamalar için kullanılıyor. Matris avantajı sağlıyor.






numpy array oluşturma 

şunu unutmayalım ki numpy bize sabit tip bilgisini zorlar. (float format) Bunu veri saklamayı minimize etmek için yapıyor. Fakat içerisinde tek tip veri tutuyor :( 


başlamadan önce 
tek boyutlu veriler vektördür 
gerisini matris diyelim 



In [20]:
import numpy as np 

b= np.array ([0,1,25,31,62,98,101,25])
type(b)



numpy.ndarray

In [24]:
np.array ([3.14,1,2,3,4,5]) # göründüğü üzere virgüllü sayı olduğu için floata zorladı 

array([3.14, 1.  , 2.  , 3.  , 4.  , 5.  ])

In [27]:
np.array ([3.14,1,2,3,4,5],dtype = "int") #sihirli parmaklar dtype yazarak formatı değiştirebilirsin :D

array([3, 1, 2, 3, 4, 5])

In [44]:
# SIFIRDAN ARRAY YAPMA SEKANSI  elindeki verileri işlemek için yapabilirsin 
np.zeros (5)

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros ((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.zeros ((3,2), dtype = "int")

array([[0, 0],
       [0, 0],
       [0, 0]])

In [50]:
np.ones (5)

array([1., 1., 1., 1., 1.])

In [51]:
np.ones ((2), dtype = "int")

array([1, 1])

In [52]:
np.full ((2,2), 4) # istediğin ibr sayı için 

array([[4, 4],
       [4, 4]])

In [56]:
np.arange (0,32,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [57]:
np.linspace (0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [60]:
np.random.normal (5,2,(2,3)) #normal dağılım fonksiyonu 5 ortalamayı ,2 ss yı temsil eder geri kalan kaça kaç matris yapmak istersen bu fonksiyon önemlidir (random)

array([[4.87319419, 3.18050633, 1.69463982],
       [5.49565268, 6.2147743 , 1.37478514]])

In [62]:
np.random.randint (0,10,(3,4)) #0 dan 10 a kadar 3e 4 lük matriste karışık integerlar dağılımla ilgilenmeyenler bunu şeçebilir.

array([[9, 8, 5, 4],
       [2, 2, 6, 4],
       [4, 3, 2, 1]])

 **_TOP 3_** 
 
    random normal  
    
    random randint
    
    arange
    
    en babaları bunlardır. Gerisi boş 

**Numpy array nesnesinin özelliklerine erişme**


ndim :  boyut sayısı

shape : boyut bilgisi

size : total eleman sayısı

dtype : array tipi

In [64]:
np.random.randint (10)

8

In [69]:
 np.random.randint (10, size = 5)

array([0, 1, 9, 8, 6])

In [70]:
 a = np.random.randint (10, size = 5)

In [71]:
a.ndim

1

In [72]:
a.shape

(5,)

In [74]:
a.size

5

In [77]:
a.dtype

dtype('int32')

In [78]:
# aynısını 2 dim arraylere de yaparsın kanzi 

In [80]:
b = np.random.randint (10, size = (3,4))

In [81]:
b

array([[4, 1, 3, 6],
       [0, 7, 0, 3],
       [0, 7, 9, 6]])

In [82]:
b.ndim

2

In [83]:
b.shape

(3, 4)

In [84]:
b.size

12

In [85]:
b.dtype

dtype('int32')

**var olan arrayi reshape yapma**

neden yapılır 

ihtiyaç halinde tek boyutu çok boyuta taşımak veya tam tersini yapmak için kullanırız.

In [94]:
c=np.arange(1,10)

In [95]:
c


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
c.reshape((3,3))  #  mesela yanii

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
x= c.reshape(1,9) #burada dikkatli bakarsan bir şeylerin değiştiğini göreceksin.

In [104]:
c.ndim


1

In [105]:
x.ndim

2

In [107]:
x # bir vektörü reshape yaparak matris formuna soktun [[ olmasının sebebi budur.


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

**BİRLEŞTİRME (concantenation)**

In [109]:
u= np.array ([1,2,3])
y= np.array ([4,5,6])

In [111]:
u

array([1, 2, 3])

In [112]:
y

array([4, 5, 6])

In [117]:
np.concatenate ( [u, y] )

array([1, 2, 3, 4, 5, 6])

**AYIRMA     (SPLİT)**

In [118]:
x= np.array ([1,2,3,44,55,66,7,8,9])

In [119]:
np.split (x, [3,6])

[array([1, 2, 3]), array([44, 55, 66]), array([7, 8, 9])]

In [120]:
a,b,c= np.split (x, [3,6])

In [121]:
a


array([1, 2, 3])

In [122]:
b


array([44, 55, 66])

In [123]:
c

array([7, 8, 9])

In [124]:
# iki boyut sekansı 

In [125]:
m= np.arange(16).reshape(4,4) 

In [126]:
m


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [127]:
np.vsplit(m,[2]) #   2 inci index E KADAR bölecen 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [128]:
x,d = np.vsplit(m,[2])

In [129]:
x


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [130]:
d

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [134]:
# vsplit hsplit buradaki mevzu yan yana koyma 

In [133]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

 **SIRALAMA (SORTİNG)**

In [135]:
m=np.array ([3,5,6,1,0,31,62])

In [137]:
np.sort(m)

array([ 0,  1,  3,  5,  6, 31, 62])

In [138]:
m

array([ 3,  5,  6,  1,  0, 31, 62])

In [139]:
m.sort()

In [140]:
m

array([ 0,  1,  3,  5,  6, 31, 62])

In [141]:
x=np.random.randint(10, size = (4,4))

In [143]:
x

array([[3, 2, 6, 9],
       [4, 8, 3, 3],
       [6, 8, 1, 5],
       [5, 2, 0, 1]])

In [144]:
x.sort()

In [145]:
x

array([[2, 3, 6, 9],
       [3, 3, 4, 8],
       [1, 5, 6, 8],
       [0, 1, 2, 5]])

In [146]:
np.sort(x, axis= 1) #yatay şekilde

array([[2, 3, 6, 9],
       [3, 3, 4, 8],
       [1, 5, 6, 8],
       [0, 1, 2, 5]])

In [147]:
np.sort(x, axis= 0) #dikine

array([[0, 1, 2, 5],
       [1, 3, 4, 8],
       [2, 3, 6, 8],
       [3, 5, 6, 9]])